services:
  app:
    build:
      context: .
    image: nextjs-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
