services:
  app:
    build:
      context: .
    container_name: nextjs-app-dev
    ports:
      - "3000:3000"
    networks:
      - next-network
    environment:
      NODE_ENV: development
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: nextjs-db-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - next-network
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  next-network:
    driver: bridge
